### ISSUE TITLE
Build failing on a Raspberry Pi 3b+32 bit

### ISSUE THREAD

**Issue by stevenm3656** [teamviewer/iotagentsdk#1]
Hi, commerical teamviewer customer here. Just found out about this SDK a few days ago and it happens that the repo is active which is nice timing! I'm having issues building the code on a raspberry pi (buster) 3b+ (32 bit) and was wondering if anyone could help or has been able to build without issues?

Some relevant information, but please ask for anything else that would be needed:

gcc and g++ version 10.1.0
cmake version 3.16.3
qt version 5.15.9
libprotoc 3.6.1
zlib 1.2.11

Command in a 'build' folder:

```
sudo rm -rf * &&
export CC=/opt/gcc-10.1.0/bin/gcc-10.1 &&
export CXX=/opt/gcc-10.1.0/bin/g++-10.1 &&
cmake -DCMAKE_PREFIX_PATH=/usr/lib/arm-linux-gnueabihf \
/home/analyzer/Downloads/iotagentsdk/
```
Configuration output:

-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /opt/gcc-10.1.0/bin/gcc-10.1
-- Check for working C compiler: /opt/gcc-10.1.0/bin/gcc-10.1 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/gcc-10.1.0/bin/g++-10.1
-- Check for working CXX compiler: /opt/gcc-10.1.0/bin/g++-10.1 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /usr/lib/arm-linux-gnueabihf/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Found gRPC: /usr/lib/arm-linux-gnueabihf/libgrpc.so  
-- Found Protobuf: /usr/lib/arm-linux-gnueabihf/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3.0") 
-- Configuring TVAgentApi to be shared
-- Configuring TVQtRC to be shared
-- Configuring Package TVAgentSDK: Version: 1.0.0, Namespace: TVAgentSDK
-- Configuring Package TVRemoteScreenSDK: Version: 1.0.0, Namespace: TVRemoteScreenSDK
-- Configuring done
-- Generating done
-- Build files have been written to: /home/analyzer/Downloads/iotagentsdk/build

Build error:

Scanning dependencies of target TVQtRC_autogen
[ 91%] Automatic MOC for target TVQtRC

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/TVQtRC/Library/export/TVQtRC/AbstractChat.h"
into
  "SRC:/build/TVQtRC/Library/TVQtRC_autogen/C6R2XQP6ZX/moc_AbstractChat.cpp"

Command
-------
/usr/local/qt5.15/bin/moc -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DTVQtRC_EXPORTS -I/home/analyzer/Downloads/iotagentsdk/build/TVQtRC/Library -I/home/analyzer/Downloads/iotagentsdk/TVQtRC/Library -I/home/analyzer/Downloads/iotagentsdk/TVQtRC/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/CommunicationLayerBase/Library/export -I/usr/local/qt5.15/include -I/usr/local/qt5.15/include/QtCore -I/usr/local/qt5.15/mkspecs/devices/linux-rasp-pi3-g++ -I/usr/local/qt5.15/include/QtGui -I/usr/local/qt5.15/include/QtQuick -I/usr/local/qt5.15/include/QtQmlModels -I/usr/local/qt5.15/include/QtQml -I/usr/local/qt5.15/include/QtNetwork -I/home/analyzer/Downloads/iotagentsdk/TVAgentAPIPrivate/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/AccessControlService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ChatService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ConnectionConfirmationService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ConnectivityService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ImageNotificationService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ImageService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/InputService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/InstantSupportService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/RegistrationService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/SessionControlService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/SessionStatusService/Library/export -I/home/analyzer/Downloads/iotagentsdk/CommunicationLayer/src/ViewGeometryService/Library/export -I/usr/include -I/opt/gcc-10.1.0/include/c++/10.1.0 -I/opt/gcc-10.1.0/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/gcc-10.1.0/include/c++/10.1.0/backward -I/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/usr/local/include -I/opt/gcc-10.1.0/include -I/opt/gcc-10.1.0/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed --include /home/analyzer/Downloads/iotagentsdk/build/TVQtRC/Library/TVQtRC_autogen/moc_predefs.h -p export/TVQtRC -o /home/analyzer/Downloads/iotagentsdk/build/TVQtRC/Library/TVQtRC_autogen/C6R2XQP6ZX/moc_AbstractChat.cpp /home/analyzer/Downloads/iotagentsdk/TVQtRC/Library/export/TVQtRC/AbstractChat.h

Output
------
/usr/local/qt5.15/bin/moc: 1: /usr/local/qt5.15/bin/moc: Syntax error: Unterminated quoted string

make[2]: *** [TVQtRC/Library/CMakeFiles/TVQtRC_autogen.dir/build.make:58: TVQtRC/Library/CMakeFiles/TVQtRC_autogen] Error 1
make[1]: *** [CMakeFiles/Makefile2:1726: TVQtRC/Library/CMakeFiles/TVQtRC_autogen.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Many thanks,

Steven

**Comment by stevenm3656** [comment]
Did a fresh clone of the repo, so that the configuration now reports:

-- Configuring Package TVAgentSDK: Version: 2.4.8, Namespace: TVAgentSDK
-- Configuring Package TVRemoteScreenSDK: Version: 2.4.8, Namespace: TVRemoteScreenSDK

Same issue.

[CMakeCache.txt](https://github.com/teamviewer/iotagentsdk/files/8785950/CMakeCache.txt)
[CMakeError.log](https://github.com/teamviewer/iotagentsdk/files/8785951/CMakeError.log)
[CMakeOutput.log](https://github.com/teamviewer/iotagentsdk/files/8785952/CMakeOutput.log)

**Comment by alexninja** [comment]
Dear Steven,

Thank you for reporting this issue. We successfully built on 32-bit Raspbian GNU/Linux 11 (bullseye) with Qt version 5.15.2.
We are working on reproducing it on an environment similar to yours and will get back to you.

In the meantime could you also please attach a copy of your file at TVQtRC/Library/CMakeFiles/TVQtRC_autogen.dir/build.make ?

Sincerely,
Alex

**Comment by alexninja** [comment]
Dear Steven,

Thank you for reporting this issue. We successfully built on 32-bit Raspbian GNU/Linux 11 (bullseye) with Qt version 5.15.2.
We are working on reproducing it on an environment similar to yours and will get back to you.

In the meantime could you also please attach a copy of your files at TVQtRC/Library/CMakeFiles/TVQtRC_autogen.dir/build.make and AutogenInfo.json ?

Sincerely,
Alex

**Comment by stevenm3656** [comment]
Hi Alex,

Thanks a lot for the quick reply, of course:

[files.zip](https://github.com/teamviewer/iotagentsdk/files/8786887/files.zip)

Thanks again,

Steven

**Comment by alexninja** [comment]
Hi Steven,

Thanks for the additional files, it doesn't look like the problem is there.

Just a quick follow-up to help us narrow it down: assuming you built qt 5.15.9 from source, did you build on the Pi itself or cross-compile?

Sincerely,
Alex

**Comment by stevenm3656** [comment]
Hi Alex,

Correct, I cross compiled.

Many thanks,

Steven

**Comment by alexninja** [comment]
Hi Steven,

We're having some trouble reproducing the issue on our end.

Do you have the ability to retry the build with stock Qt libs obtained through apt, instead of this latest version?

Also, this is a long shot, but could you double check whether you have any paths with quotes in them (single or double)? I was able to get "Syntax error: Unterminated quoted string" if I used a build directory with a ' in the name, although not exactly like the error you're seeing.

Best regards,
Alex

**Comment by stevenm3656** [comment]
Hi Alex,

Apologies for the delayed response, unfortunately the answer is no to both. I am going to have to leave this task for a while but if I find a solution at a later date, I will make sure to comment back.

Thank your for your effort and help,

Steven

**Comment by alexninja** [comment]
Hi Steven,

We were able to build with Qt 5.15.9 on a 32-bit Raspberry Pi (Bullseye). We will try to rule out cmake versions next. At the moment, one possibility is that the issue may be related to your environment -- although I don't see anything out of the ordinary at first glance.

If you find time to get back to the issue and happen to track it down, we would be happy to hear about it. Perhaps running cmake in verbose mode could pinpoint the source of the "unterminated quoted string" error.

Could you also take a look at this thread https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads -- `cannot find -lpthreads` may not be the real error, but there might be others before it, such as a missing package.

Sincerely,
Alex

**Comment by kko-dev** [comment]
Hi Steven,

we more and more suspect that the problem could be with the Qt setup. We would have expected more output for Qt in your CMake cache. Is it possible for you to build any other Qt application on this pi? Something like a simple hello world.

We are very eager to help you, but we think we need a dedicated session with you. Could you open a supporter ticket at support@teamviewer.com where you leave your contact data? We will reach out to you and will schedule a session with you.

Sincerely,
Korbinian

**Comment by stevenm3656** [comment]
Hi Alex and Korbinian,

Apologies for the late response. The Qt version works, I was able to build our in-house software with it. The reason I was looking at TV IoT was because the latest versions of TV on the Pi have some issues, locking up after a file transfer etc.

Eventually I had to settle for using an older version of TV  (5.15.5) for the Pi. We are a small development team and have to move onto other things.

Thanks for the time you have both taken on this, I will close as it cannot be reproduced.

Steven

**Comment by alexninja** [comment]
Hi Steven,

Thank you for your feedback. 

By the way, for file transfer and/or remote screen, you don't need the full TV client; the IoT Agent alone will suffice. (The Agent SDK is not necessary.)

**Enable file transfer**:
(yes, that's indeed a 0)

```
sudo teamviewer-iot-agent configure set FileTransferAccessControl 0
```

**Enable remote screen**:

```
sudo teamviewer-iot-agent configure set EnableRemoteScreen 1
```

To use remote screen through the framebuffer (view only):

```
sudo teamviewer-iot-agent configure set RemoteScreenChannels 'FBD:/dev/fb0'
```

To use remote screen through X11 (with keyboard/mouse input):

```
sudo teamviewer-iot-agent configure set RemoteScreenChannels 'X11'
sudo startx &
```

For more details about options:

```
sudo teamviewer-iot-agent --help
sudo teamviewer-iot-agent configure --help
```

Or refer to the online KB article: https://community.teamviewer.com/English/kb/articles/58731-teamviewer-iot-remote-screen

Best regards,
Alex
